In [1]:
import os
import json
from openai import OpenAI


PROMPT = """
你的角色：你是一位经验丰富的电商广告文案专家，尤其擅长撰写生动、吸引人且能促进销售的服装类商品描述。

任务：请根据用户提供的【关键词列表】，为一件商品创作一篇完整的广告文案。

背景信息与输入：
关键词：用户将提供一组由“属性#值”构成的关键词，详细描述了商品的类型、版型、风格、图案、款式等特征。

示例参考：
输入关键词：类型#上衣*版型#宽松*风格#街头*风格#休闲*风格#朋克*图案#字母*图案#文字*图案#印花*衣样式#卫衣*衣款式#连帽*衣款式#对称
输出文案示例：个性休闲风的连帽卫衣造型时髦大方，宽松的版型剪裁让肉肉的小宝贝也可以穿着，保暖的连帽设计时刻给予宝贝温柔的呵护，袖子和后背别致时髦的字母印花点缀，满满的街头元素融入，演绎休闲朋克风，对称的小口袋美观大方，方便放置更多的随身物品。

文案创作要求：
完整性：生成的文案必须是一段通顺、完整、可直接使用的商品描述段落。
信息整合：需要自然地涵盖并突出关键词中提供的所有核心属性（如版型、风格、图案、款式等），不能遗漏关键词和卖点。
语言风格：语言应 亲切、有感染力、具有销售力。适当使用引导语，描绘穿着场景和感受，激发购买欲望。
目标导向：文案的目的是促进销售，因此要突出商品的优势、解决用户的痛点（如“宽松版型”修饰身材）、并描绘穿着后的美好体验。

输出格式：
记住，只输出最终的广告文案，无需额外解释或输出其他内容。

关键词：{}
输出："""

llm_client = OpenAI(
    api_key="xxxx",
    base_url="https://ark.cn-beijing.volces.com/api/v3"
)

def request_chat(query, answer=""):    
    try:
        prompt = PROMPT.format(query)

        completion = llm_client.chat.completions.create(
            model="doubao-seed-1-6-251015",
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=2048,
            temperature=0.6
        )
        result = completion.choices[0].message.content
        return query, answer, result
        
    except:
        return query, "", ""

In [2]:
# 测试
query = "类型#上衣*风格#淑女*衣样式#毛衣*衣领型#高领"
_, _, res = request_chat(query)
print(res)

这件温柔淑女风的高领毛衣简直是优雅女孩的秋冬必备上衣！软糯细腻的毛衣质地，贴肤穿着亲肤又保暖；经典的高领设计，既能牢牢锁住颈部温暖抵御寒风，又能悄悄修饰颈部线条，让你看起来更显精致小巧。整体风格透着满满的淑女温婉感，不管是搭配飘逸的半身裙去约会，还是配简约直筒裤通勤，都能轻松穿出优雅大方的模样，穿上它你就是人群中那个温柔又有品味的小仙女呀，谁能不爱呢～

In [3]:
import pyarrow.parquet as pq
train_parquet_file = pq.ParquetFile('data/train-00000-of-00001-5924736d8b9825b5.parquet')
valid_parquet_file = pq.ParquetFile('data/validation-00000-of-00001-b01a1a8dd8034cf6.parquet')
train_table = train_parquet_file.read().to_pandas()
valid_table = valid_parquet_file.read().to_pandas()
train_table

,content,summary
0,类型#裤*版型#宽松*风格#性感*图案#线条*裤型#阔腿裤,宽松的阔腿裤这两年真的吸粉不少，明星时尚达人的心头爱。毕竟好穿时尚，谁都能穿出腿长2米的效果...
1,类型#裙*风格#简约*图案#条纹*图案#线条*图案#撞色*裙型#鱼尾裙*裙袖长#无袖,圆形领口修饰脖颈线条，适合各种脸型，耐看有气质。无袖设计，尤显清凉，简约横条纹装饰，使得整身...
2,类型#上衣*版型#宽松*颜色#粉红色*图案#字母*图案#文字*图案#线条*衣样式#卫衣*衣款...,宽松的卫衣版型包裹着整个身材，宽大的衣身与身材形成鲜明的对比描绘出纤瘦的身形。下摆与袖口的不...
3,类型#裙*版型#宽松*材质#雪纺*风格#清新*裙型#a字*裙长#连衣裙,踩着轻盈的步伐享受在午后的和煦风中，让放松与惬意感为你免去一身的压力与束缚，仿佛要将灵魂也寄...
4,类型#上衣*材质#棉*颜色#蓝色*风格#潮*衣样式#polo*衣领型#polo领*衣袖长#短...,想要在人群中脱颖而出吗？那么最适合您的莫过于这款polo衫短袖，采用了经典的polo领口和柔...
...,...,...
114594,类型#上衣*风格#运动*风格#休闲*衣样式#外套*衣领型#立领*衣袖长#长袖*衣门襟#拉链*...,基础的外套廓形，直筒，立领长袖，中间金属拉链穿脱，方便实用，带有浓浓的休闲运动味道。日常休闲...
114595,类型#上衣*风格#街头*图案#创意*衣样式#卫衣,在这件卫衣上，BRAND-white集合了女性化的柔美还有不变的街头风采，<UNK><UNK...
114596,类型#裙*版型#宽松*版型#显瘦*颜色#黑色*图案#撞色*裙型#直筒裙*裙款式#拼接,采用简洁大体的黑色格调，宽松舒适的裙子内里，配上落肩的袖子拼接，不惧夏日的炎热，穿出清凉舒适...
114597,类型#上衣*颜色#黑色*颜色#紫色*风格#性感*图案#字母*图案#文字*图案#线条*图案#刺...,卫衣的短款长度设计能够适当地露出腰线，打造出纤瘦的身材十分性感。衣身的字母刺绣图案有着小巧的...
114598,类型#上衣*颜色#黑白*风格#简约*风格#休闲*图案#条纹*衣样式#风衣*衣样式#外套,设计师以条纹作为风衣外套的主要设计元素，以简约点缀了外套，带来大气休闲的视觉效果。因为采用的...

In [4]:
valid_table

,content,summary
0,类型#上衣*材质#牛仔布*颜色#白色*风格#简约*图案#刺绣*衣样式#外套*衣款式#破洞,简约而不简单的牛仔外套，白色的衣身十分百搭。衣身多处有做旧破洞设计，打破单调乏味，增加一丝造...
1,类型#裙*材质#针织*颜色#纯色*风格#复古*风格#文艺*风格#简约*图案#格子*图案#纯色...,这款BRAND针织两件套连衣裙，简约的纯色半高领针织上衣，修饰着颈部线，尽显优雅气质。同时搭...
2,类型#上衣*风格#嘻哈*图案#卡通*图案#印花*图案#撞色*衣样式#卫衣*衣款式#连帽,嘻哈玩转童年，随时<UNK>，没错，出街还是要靠卫衣来装酷哦！时尚个性的连帽设计，率性有范还...
3,类型#裤*风格#英伦*风格#简约,裤子是简约大方的版型设计，带来一种极简主义风格而且不乏舒适优雅感，是衣橱必不可少的一件百搭单...
4,类型#裙*裙下摆#弧形*裙腰型#高腰*裙长#半身裙*裙款式#不规则*裙款式#收腰,这款来自梵凯的半身裙富有十足的设计感，采用了别致的不规则设计，凸显出时尚前卫的格调，再搭配俏...
...,...,...
1065,类型#裤*版型#宽松*材质#亚麻*裤长#九分裤*裤长#连体裤*裤款式#勾花镂空*裤腰型#松紧腰,这款连体裤版型宽松，对衣者的身材要求没有过多要求；九分裤设计则是小个子妹子们不可错过的显高武...
1066,类型#裙*版型#宽松*版型#显瘦*裙领型#圆领*裙款式#勾花镂空*裙款式#纽扣,<UNK>让你孕期也能魅力依旧，经典的圆领，更具百搭感，宽松的镂空袖子设计，让裙子更立体，同...
1067,类型#裤*版型#显瘦*材质#牛仔布*颜色#深蓝色*裤腰型#高腰,misssixty的这条牛仔裤采用了时尚大气的烟灰色，改变了常规的深蓝色带来的审美疲劳。它是...
1068,类型#裤*材质#牛仔布*颜色#白色*风格#简约*图案#线条*裤长#短裤*裤型#阔腿裤*裤腰型...,设计剪裁立体有心意，穿着更加有型有范儿。设计师匠心独制，高腰阔腿设计修饰腿部线条为此款白色牛...
1069,类型#裙*版型#显瘦*材质#网纱*风格#性感*裙型#百褶*裙下摆#压褶*裙长#连衣裙*裙衣门...,内搭的连衣裙，几乎每个人都有一件。但是像这件这么性感妩媚的很少，没有拉链，套头就可以穿，网纱...

In [ ]:
import json
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed 

max_workers = 200
n_samples = 45000

inputs = train_table["content"][:n_samples]
answer = train_table["summary"][:n_samples]

fw = open("data/train_dpo.json", "w")

# 使用多进程并行调用生成答案
with ProcessPoolExecutor(max_workers=max_workers) as executor:
    futures = [executor.submit(request_chat, query, answer) for query in zip(inputs, answer)]
    for future in tqdm(as_completed(futures), total=len(inputs), desc="Generations"):
        query, answer, better_answer = future.result()
        if len(better_answer) > 100 and len(better_answer) < 500 and "think_never_used" not in better_answer: # 答案不能太短或太长
            info = {"prompt": query, "chosen": better_answer, "rejected": answer}
            fw.write(json.dumps(info, ensure_ascii=False) + "\n")
fw.close()

Generations:   0%|          | 0/40000 [00:06<?, ?it/s]

In [ ]:
inputs = valid_table["content"]
answer = valid_table["summary"]

fw = open("data/test_dpo.json", "w")

# 使用多进程并行调用生成答案
with ProcessPoolExecutor(max_workers=max_workers) as executor:
    futures = [executor.submit(request_chat, query, answer) for query in zip(inputs, answer)]
    for future in tqdm(as_completed(futures), total=len(inputs), desc="Generations"):
        query, answer, better_answer = future.result()
        if len(better_answer) > 100 and len(better_answer) < 500 and "think_never_used" not in better_answer: # 答案不能太短或太长
            info = {"prompt": query, "chosen": better_answer, "rejected": answer}
            fw.write(json.dumps(info, ensure_ascii=False) + "\n")
fw.close()